[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.9.3"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# API routes must go to Netlify functions, not static HTML
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Static fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Content Security Policy headers to fix Privy and WalletConnect issues
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://js.stripe.com https://*.privy.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://*.stripe.com https://*.privy.io https://sepolia.base.org https://explorer-api.walletconnect.com https://rpc.walletconnect.com https://infragrid.v.network; frame-src 'self' https://js.stripe.com https://hooks.stripe.com https://auth.privy.io; object-src 'none'; base-uri 'self'; form-action 'self' https://api.stripe.com https://hooks.stripe.com; frame-ancestors 'self';"
