[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.9.3"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
